[Variables]

Color1=255,255,255, 255                         >>> all strings <<< 
Color2=255,255,255,  180                       >>> filling lines <<<
Color3=255,255,255,  20                          >>>  empty lines :D <<<
Color4=0,255, 255, 100
Color5=0,255, 255, 200
FontName=Imagine font
FontNamexxx=Good Times
Font=HandelGotDLig
Font2=Imagine font
Font3=Nasalization
FontHeight=7
FontHeight1=8
FontHeight2=7
FontHeight3=6
FontHeight4=5
InternetSpeedDl=262144
InternetSpeedUp=51200
fontColor.Text=255, 255, 255, 200
fontColor.Text1=0,255, 255,255
fontColor.TextOn=0,255, 255,255
border.color=0,255, 255, 100
FontGrafity="Webdings"
FontGrafityHeight=14





Style=Normal
Style2=Bold
AntiAlias=1
FontColor.Text2=255,255,255,150
Effect=SHADOW
EffectColor=0, 0, 0, 0


 
FH=70
FW=70





FirstString=60



XL=120
YL=5



FolderCountText=%1 folders

FileCountText=%1 items %2B



; file timpe will show in skin only certain file tipe, also it will show only the size of those file tipes
; Eg. to complete the field *.doc;*.mp3;*.jpg
;leve blank for all files
;Text Orientation have those values 1=string meters on left; 2=string meters on left hidden; 3=string meters on right; 4=string meters on right hidden;
;NOTE that the skin when opens the text is visible, after mouse over the icon the text will hide


Path1=C:\Users\Burnwell\Pictures
Icon1=#SKINSPATH#NEW SKIN\icons\F2.png
Folder1=Pictures
FileType1=
TextOrientation1=3

Path2=C:\Users\Burnwell\Documents\Rainmeter\Skins
Icon2=#SKINSPATH#NEW SKIN\icons\F3.png
Folder2=Skins
FileType2=
TextOrientation2=1

Path3=C:\Users\Burnwell\Downloads
Icon3=#SKINSPATH#NEW SKIN\icons\F1.png
Folder3=Downloads
FileType3=
TextOrientation3=1

Path4=D:\Muzica
Icon4=#SKINSPATH#NEW SKIN\icons\F4.png
Folder4=Muzica
FileType4=*.mp3
TextOrientation4=3

[StringStyle]
FontColor=#Color1#
FontFace=#Font2#
FontSize=6
StringEffecx=NONE
StringStyle=BOLD
StringAlign=LEFT
AntiAlias=1